backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{book}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Chapter", name: "chapter", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Chapter Number", name: "chapter_number", widget: "string"}
      - {label: "B&N", name: "bn", widget: "string"}
      - {label: "Amazon", name: "amazon", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}